# Numpy

### Cara Untuk mengakses / mengubah element,kolom,baris, dan lainya 

In [1]:
import numpy as np

In [6]:
a = np.array([[2,4,5,1,34,6],[3,4,6,2,1,7]])
a

array([[ 2,  4,  5,  1, 34,  6],
       [ 3,  4,  6,  2,  1,  7]])

In [7]:
#mendapatkan element tertentu[baris,column]
a[1,2]

6

In [14]:
#mendapatkan spesifik isi baris
a[0,:]

array([ 2,  4,  5,  1, 34,  6])

In [12]:
#mendapatkan spesifik isi kolom
a[:,2]

array([5, 6])