# Numpy

### Cara Untuk mengakses / mengubah element,kolom,baris, dan lainya 

In [83]:
import numpy as np

In [14]:
a = np.array([[2,4,5,1,34,6],[3,4,6,2,1,7]])
a

array([[ 2,  4,  5,  1, 34,  6],
       [ 3,  4,  6,  2,  1,  7]])

In [7]:
#mendapatkan element tertentu[baris,column]
a[1,2]

6

In [14]:
#mendapatkan spesifik isi baris
a[0,:]

array([ 2,  4,  5,  1, 34,  6])

In [9]:
#mendapatkan spesifik isi kolom
a[:,2]

array([5, 6])

In [15]:
#mengubah nilai di kolom dan baris tertentu

a[1,3] = 2
print(a)


[[ 2  4  5  1 34  6]
 [ 3  4  6  2  1  7]]


contoh matriks / array 3 dimensi

In [19]:
b = np.array([[[3,4],[38,34]],[[23,4],[3,4]]])
b

array([[[ 3,  4],
        [38, 34]],

       [[23,  4],
        [ 3,  4]]])

### mengenal beberapa tipe array dengan numpy

In [30]:
#array dengan nilai 0
np.zeros((3,4))
#np.zeros((5,3,5))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
#matriks identitas
np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [38]:
#matriks full dengan angka yang sama
np.full((3,3),11,dtype='float32')

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]], dtype=float32)

In [41]:
#menggunakan full_like
np.full_like(b,2)

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [49]:
#membuat matriks dengan angka random desimal
np.random.rand(2,4)

array([[0.17693625, 0.90419829, 0.02042186, 0.65553761],
       [0.94998121, 0.04861704, 0.52392773, 0.06480895]])

In [79]:
#membuat matriks dengan angka random integer
np.random.randint(1,5,size=(3,3))

array([[1, 4, 1],
       [4, 3, 1],
       [2, 2, 2]])

In [81]:
#matriks identitas
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [100]:
#studi kasus
satu = np.ones([5,5])
print(satu)

nol = np.zeros((3,3))
print(nol)

nol[1,1] = 4
print(nol)
satu[1:-1,1:-1] = nol
print(satu)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 4. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### matematika di matrik

In [103]:
d = np.array([2,4,8,6])
print(d)

[2 4 8 6]


In [105]:
#penjumlahan
d + 2

array([ 4,  6, 10,  8])

In [106]:
#pengurangan
d - 4

array([-2,  0,  4,  2])

In [107]:
#perkalian
d * 3

array([ 6, 12, 24, 18])

In [108]:
#pembagian
d /2

array([1., 2., 4., 3.])

In [111]:
e = np.array([3,4,6,7])
d + e

array([ 5,  8, 14, 13])

In [113]:
#pangkat
d ** 2

array([ 4, 16, 64, 36], dtype=int32)

In [117]:
#melihat hasil sin ,cos ,tan
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[ 0.90929743 -0.7568025  -0.95892427  0.84147098  0.52908269 -0.2794155 ]
 [ 0.14112001 -0.7568025  -0.2794155   0.90929743  0.84147098  0.6569866 ]]
[[-0.41614684 -0.65364362  0.28366219  0.54030231 -0.84857027  0.96017029]
 [-0.9899925  -0.65364362  0.96017029 -0.41614684  0.54030231  0.75390225]]
[[-2.18503986  1.15782128 -3.38051501  1.55740772 -0.62349896 -0.29100619]
 [-0.14254654  1.15782128 -0.29100619 -2.18503986  1.55740772  0.87144798]]
